# Generated by Django 5.1.7 on 2026-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
