# Generated by Django 5.1.7 on 2026-04-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='activate',
            new_name='active',
        ),
    ]
